name: Alt Capstone 
run-name: ${{ github.actor }} pushed a commit to main
on:
  push:
    branches:
      - main

env:
  ARM_CLIENT_ID: "${{ secrets.TF_VAR_CLIENT_ID }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.TF_VAR_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.TF_VAR_TENANT_ID }}"
  ARM_CLIENT_SECRET: "${{ secrets.TF_VAR_CLIENT_SECRET }}"


jobs:
  Capstone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Install Kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

      - name: Apply terraform
        run: |
          terraform init
          terraform apply --auto-approve
        working-directory: infra

      - name: Authenticate Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
      - name: Azure cluster creds
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az aks get-credentials --name ay-capstone --resource-group alt-school-capstone

      - name: Apply Manifests to cluster
        run: |
          kubectl apply -f alerting
          kubectl apply -f monitoring
          kubectl apply -f socks-shop
        



          
